version: "3"
services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    depends_on:
      - postgres
      - sqs
    env_file:
      - dev.env
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  postgres:
    image: postgres:12.0
    ports:
      - "25432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: zoo
      POSTGRES_PASSWORD: zoo
      POSTGRES_DBNAME: zoo

  localstack:
    image: localstack/localstack
    ports:
      - "4566"
    environment:
      - SERVICES=sqs
      - PORT_WEB_UI=8080
      - DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "~/tmp/localstack:/var/lib/localstack."
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./localstack_bootstrap:/docker-entrypoint-initaws.d/