version: "3"
services:
  app:
    build:
      dockerfile: ./docker/dev/Dockerfile
      context: .
    depends_on:
      - postgres
    env_file:
      - dev.env
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  postgres:
    image: postgres:12.0
    ports:
      - "25432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: zoo
      POSTGRES_PASSWORD: zoo
      POSTGRES_DBNAME: zoo